// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package http

import (
	"github.com/aristat/slack-bot/internal/app/bot"
	"github.com/aristat/slack-bot/internal/app/logger"
	"github.com/aristat/slack-bot/internal/app/router"
)

// Injectors from injector.go:

// Build
func Build() (*HTTP, func(), error) {
	chiMux, cleanup, err := Mux()
	if err != nil {
		return nil, nil, err
	}
	logrusLogger, cleanup2, err := logger.Provider()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	slack, cleanup3, err := bot.Provider(logrusLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	routerRouter, cleanup4, err := router.Provider(slack)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	http, cleanup5, err := Provider(chiMux, routerRouter, logrusLogger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return http, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
